[maze_colors]
cell     = "#EF233C"
road     = "#C5560C"
wall     = "#7A1520"
padding  = "#28080E"
backdrop = "#180508"
shadow   = "#EF233C"

[locations]
start  = "#FFD700"
end    = "#4CC9F0"

[menu_colors]
text   = "#FFE0E4"
button = "#EF233C"
bg = "#28080E"
