[maze_colors]
cell      = "#0FF0FC"
road      = "#003B3F"
wall      = "#00C8D4"
padding   = "#001820"
backdrop  = "#000C10"
shadow    = "#008B96"
[locations]
start     = "#F5FF00"
end       = "#FF00C8"
[menu_colors]
text      = "#C0FFFF"
button    = "#0FF0FC"
bg        = "#001820"
