[maze_colors]
cell     = "#AF03DE"
road     = "#4D3678"
wall     = "#1E0C35"
padding  = "#332155"
backdrop = "#8B41EB"
shadow   = "#431668"

[locations]
start  = "#00F5D4"
end    = "#FFD700"

[menu_colors]
text   = "#E8E0FF"
button = "#9D4EDD"
