[maze_colors]
cell     = "#AAFF00"
road     = "#223602"
wall     = "#3A5500"
padding  = "#152200"
backdrop = "#0D1500"
shadow   = "#AAFF00"

[locations]
start  = "#FF6B35"
end    = "#F72585"

[menu_colors]
text   = "#F0FFD0"
button = "#AAFF00"
